Fix comments being duplicated on refresh
GetStream/swift-activity-feed pull request #8
Opened 2020-05-22 15:34 UTC by cardoso

2020-05-22 15:43 UTC, cardoso commented
The bug happens because it's not reaching this path in ReactionPaginator's load function due to the Pagination being .limit(100):
```swift
if case .none = pagination {
    self.items = []
    self.next = .none
}
```

So I just changed it to .none (default) like it's done for the FlatFeed .

2020-05-26 15:59 UTC, b-onc commented
@cardoso Your observation is right, paginator is not removing items when `load` is called with a pagination option. IMHO this is a bug, `load` should not `append` items, it should load from start and `loadNext` should append the items.
So
```swift
if case .none = pagination {
  self.items = []
  self.next = .none
}
```
should be
```swift
if pagination != next {
  self.items = []
  self.next = .none
}
``` 
or a similar logic to make sure `load` and `loadNext` behaves differently.
Since this changes a lot of things (Pagination is not Equatable), I suggest introducing `reset` function to `PaginatorProtocol` to reset items (`items = []`) and putting these calls before `load(.limit(100))`s in `DetailViewController`, which will make sure we won't get replicated items.
 This bug is probably affecting other places but we don't know yet, this is the easiest and safest solution.

2020-05-26 19:13 UTC, cardoso commented
@b-onc changes made

2020-05-27 13:16 UTC, b-onc requested changes
You have to add a `reset` call to `DetailViewController.swift:L377` and `L:492` too

2020-05-27 17:00 UTC, cardoso commented
@b-onc nice catch. Since it's in so many places, I also introduced separate function for it.

2020-05-28 11:13 UTC, b-onc requested changes
The commit history is polluted, it has commits from PR #7. Can you rebase so it has only has commits related to this PR?

2020-05-28 11:13 UTC, b-onc commented on Sources/Components/Flat Feed/DetailViewController.swift
> +    private func resetComments() {
I suggest renaming this to `reloadComment`

2020-05-29 02:15 UTC, cardoso commented
Should be fine now @b-onc

2020-05-29 10:04 UTC, b-onc approved these changes

2020-05-29 10:04 UTC, merged